### ISSUE TITLE
not working on latest firefox nightly

### ISSUE THREAD

**Issue by pcause** [JustOff/cookies-exterminator#1]
I am using firefox nightly.  i have legacy extensions enabled.  the icon isn't showing up.  if I open preferences it won't let me put on automatic mode.  says i need to have something in whitelist.  try to add and looks ok, but if i open preferences again the item i added isn't there.

**Comment by JustOff** [comment]
Resolved by https://github.com/JustOff/cookies-exterminator/commit/d56a7d5e0a0058010b60e736ac29e5e1ba72af8d
