### ISSUE TITLE
Reset button not working

### ISSUE THREAD

**Issue by Gittyperson** [JustOff/cookies-exterminator#10]
Trying to reset Options and clear the Whitelist but the Reset button doesn't seem to do anything.

CE 2.9.4, Pale Moon 28.0.0b5 x64 (2018-08-01), Windows 10

**Comment by JustOff** [comment]
Reset button does not reset options and domain lists to defaults, but to the state when the Preferences dialog was open. This is intended for Linux and MacOS, where there is no Apply button and any changes are always applied immediately.
