### ISSUE TITLE
Cookies are not deleted in Waterfox

### ISSUE THREAD

**Issue by amrgul** [JustOff/cookies-exterminator#11]
Waterfox 56.2.2, CE 2.9.4, active mode is on, clear session cookies on, clear local storage on, clear indexed db on. 
Cookies are not deleted when tabs are opened but not used.

**Comment by JustOff** [comment]
Cookies Exterminator automatically erases cookies, localStorage and IndexedDB objects when they are no longer used by open browser tabs. This means that any open tab protects its objects until it's closed. There is no other way to guess if the user wants to keep them.

**Comment by amrgul** [comment]
But I remember before it was deleting cookies even when tabs were open but I was on a different webpage for a certain amount of time period like 10 sec. Do I remember things incorrectly? - sorry if so.

**Comment by JustOff** [comment]
I'm afraid you're getting wrong, it always behaved in this way.

**Comment by amrgul** [comment]
May I to have one more question: if I set "privacy.firstparty.isolate" true, will this affect on CE?

**Comment by JustOff** [comment]
[Unfortunately, FPI isn't supported by CE](https://github.com/JustOff/cookies-exterminator/issues/7#issuecomment-387485340).
