### ISSUE TITLE
Reset button doesn't work in option page

### ISSUE THREAD

**Issue by ribatamu** [JustOff/cookies-exterminator#12]
I have Firefox ESR 52.9, Windows 10 and Cookies Exterminator 2.9.4.

Open the cookies exterminator option page. On top we have the tabs: Options, Whitelist, Greylist, Redlist and Log. On bottom we have  the tabs: Reset, Accept and Cancel. 

Pressing the Reset option and accept it doesn't change the values to default.

**Comment by JustOff** [comment]
See [here](https://github.com/JustOff/cookies-exterminator/issues/10#issuecomment-412125078).
