### ISSUE TITLE
Cookies Exterminator does not work with Pale Moon 28.0.0

### ISSUE THREAD

**Issue by lashkevi** [JustOff/cookies-exterminator#13]
Cookies Exterminator does not work with Pale Moon 28.0.0. Though the icon is present and red, cookies are not deleted neither after closing tabs nor after restarting Pale Moon.

**Comment by JustOff** [comment]
I successfully use CE with PM28 every day for three months already. Perhaps you have some conflict with other add-ons or browser settings. Please try to start from a clean profile.
