### ISSUE TITLE
Toolbar button changes status bar behavior

### ISSUE THREAD

**Issue by silverwings15** [JustOff/cookies-exterminator#14]
hey JustOff. found this small bug when i decided to move the CE toolbar button to the status bar, and then hiding the status bar (Ctrl - /). after each restart of the browser, the status bar becomes visible by itself despite hiding it before restarting. disabling CE fixes this behavior

W10 x64, CE 2.9.4, PM 28.1.0

**Comment by JustOff** [comment]
This behavior is by design. Do you really need to hide toolbars that contain buttons?

**Comment by silverwings15** [comment]
hmm, i usually stick all the extensions' toolbar buttons into the status bar, opening it only when needed. really helps to avoid visual clutter, as i have a lot of toolbar buttons from all my extensions.

but knowing that this is by design, i can work around it no biggie.

**Comment by JustOff** [comment]
I can add a hidden pref to not restore the status bar (like it was done [here](https://forum.palemoon.org/viewtopic.php?p=113307#p113307)), if you greatly suffer from this.

**Comment by silverwings15** [comment]
thanks for the offer but it's really no big deal, don't worry about it!
