### ISSUE TITLE
Minor translation mistake

### ISSUE THREAD

**Issue by Herb0yk** [JustOff/cookies-exterminator#15]
When I import data in the german localiization it reports "Successful export"
At least it confused me to run a second import, hoewever it did the job anyway.

**Comment by JustOff** [comment]
Yes indeed, thanks. Could you suggest a correct translation for the [ImportOK](https://github.com/JustOff/cookies-exterminator/blob/master/locale/de/cookies-xtrm.properties#L28) string?

**Comment by JustOff** [comment]
@Herb0yk ?

**Comment by Herb0yk** [comment]
My e-mail reply didn't reach you?
Just replace the "Ex" by "Im"

**Comment by JustOff** [comment]
Thank you! This fix will be included in the next release.
