### ISSUE TITLE
Reducing crushing delay under 10 seconds

### ISSUE THREAD

**Issue by mstempell** [JustOff/cookies-exterminator#16]
Could the crushing delay be reduced under 10 seconds?
Any reason for this minimal delay?

I can enter a lower delay in the options field, but it resets to 10 when closing the options window by clicking 'Accept'.

**Comment by JustOff** [comment]
> Could the crushing delay be reduced under 10 seconds?

Unfortunately not.

> Any reason for this minimal delay?

This is a both performance and implementation compromise.

**Comment by mstempell** [comment]
OK i'll live with that wait time, when getting out of websites from notoriously tracking corporations then. ;)
Thanks for the explanation (that could be stated in the readme i'd say).

And thanks for your work on the various extensions for Pale/New Moon.

**Comment by JustOff** [comment]
You are welcome!
