### ISSUE TITLE
Version for Waterfox Current?

### ISSUE THREAD

**Issue by rebop** [JustOff/cookies-exterminator#20]
Absolutely my favorite cookie extension and use daily in Waterfox Classic. Palemoon version does not seem to work in Waterfox Current. Any chance of a port? Cannot find anything that comes close. Thanks.

**Comment by JustOff** [comment]
> Any chance of a port?

Not really.

> Cannot find anything that comes close.

Take a look at [Cookie AutoDelete](https://addons.mozilla.org/en-US/firefox/addon/cookie-autodelete/).

**Comment by rebop** [comment]
Thanks, but not as easy to whitelist. Shame there will not be an update. But thanks for the reply.
