### ISSUE TITLE
Cookie leftovers found by CCleaner

### ISSUE THREAD

**Issue by ghysler** [JustOff/cookies-exterminator#21]
If I scan for cookies with CCleaner, after exterminating cookies with your add-on, they still show up in CCleaner with their name and 0KB in size. In Pale Moon these cookies are not found anymore though. I don't know what internal process CCleaner uses for cookie searching, but this worries me a bit. If I clean the cookies with CCleaner, they do stop showing in the results.

In the add-on config I have enabled all three 'clear' options (default setting), and enabled 'active mode'. 

Steps to reproduce:

1) visit github.com
2) close browser window
3) restart browser to verify cookie is removed from browser
4) use CCleaner and scan section: Firefox -> Cookies
5) github.com cookie shown in results window

**Comment by JustOff** [comment]
Hopefully, in the second step, you had more than one browser window and you waited for CE to delete cookies after closing the github window. Also, there is no need to restart the browser for the cookies to be deleted.

Either way, I cannot confirm that there are any problems. You can [check](https://inloop.github.io/sqlite-viewer/) the moz_cookies table in the cookies.sqlite file in the profile directory to ensure that CE is working as expected.

**Comment by ghysler** [comment]
> Hopefully, in the second step, you had more than one browser window and you waited for CE to delete cookies after closing the github window. Also, there is no need to restart the browser for the cookies to be deleted

I was actually wondering how this would work, when closing Pale Moon completely instead of just the tab. 

On my end all (not whitelisted) cookies are instantly removed when closing the browser completely. I have just confirmed this by checking the contents of cookies.sqlite. This is also the preferred outcome for me. But I understand now it is not supposed to work like this? If I disable the Cookies Exterminator add-on, the cookies remain when closing the browser. I also have no other cookie manager add-ons active and Pale Moon is set to "keep cookies until they expire".

Anyway, since the cookies are indeed removed from cookies.sqlite, do you have any idea why CCleaner still finds remaining cookie data? Have you tried testing this with CCleaner? You can find the portable version here: https://www.ccleaner.com/ccleaner/builds I'm curious if you see the same results.

**Comment by JustOff** [comment]
CE is designed to remove cookies on browser startup and shutdown, as well as on closing tabs and windows. But only in the latter case, you can track what is happening using notifications and logs, and the contents of the cookies.sqlite file are relevant only when the browser is closed.

The point is, I'm not at all sure if CCleaner works with Pale Moon correctly when you choose to scan Firefox cookies. And, sorry, but I will not try to figure it out, as I have too many different versions of Firefox and Pale Moon using different profiles simultaneously installed on my computer.

I hope I answered all the questions and dispelled your doubts.

**Comment by ghysler** [comment]
Frankly, I'm a little surprised that you, as the maintainer of an add-on that is responsible for clearing cookies, are not interested in investigating this issue further (eg. use a VM env for testing), and assign an incorrect label to this issue.

In the meantime I did some digging of my own. Apparently the cookies listed in CCleaner -after- removing cookies with CE are retrieved from the profile file "SiteSecurityServiceState.txt", which contains the so called "supercookies" (HSTS data). More information can be found here: http://forums.mozillazine.org/viewtopic.php?f=23&t=2919581
If you clean "Site Preferences" from within the browser, this data will also be cleaned (but not just this data, so be careful).

Since these "supercookies" are a privacy concern, I guess it's a nice touch that CCleaner also removes this data. Though I'm assuming you're not interested in including this option in CE.

**Comment by JustOff** [comment]
Sorry, but HSTS data has nothing to do with cookies; you can disable it completely via `network.stricttransportsecurity.enabled`.
