### ISSUE TITLE
Separate timer for cookies from visited sites

### ISSUE THREAD

**Issue by gh-ix** [JustOff/cookies-exterminator#3]
Thank you very much for that nice addon!
I think to make it generally usable for useres who are not cookie/web-tech aware, there should be a second timer which handles cookies from visited sites.

Advantage: Lazy Users don't nedd to bother with grey/whitelists
Disadvantage: JustOff unpaid time
Effort: Medium to low I guess: CE determines if cookies are to be deleted by the status of "open" URLs, so all information should be present already and it's just about adding the timer, the logic and a user changable preferences option.

Example:
Say I visit www.inter.net and get cookies from singleklick.net, inter.net and some more.
Now if I get redirected from www.inter.net to pay.3rdpartybank.net, I'd love to see cookies beeing deleted after 10 seconds which came from singleklick.net, but the ones which came from inter.net shouldn't be deleted before a much longer timeout lapses - say 10 minutes. So I can safely pay and return within 10 minutes without having to remember to switch to grey!

**Comment by JustOff** [comment]
Sorry, but I doubt that such logic can bring useful results.
