### ISSUE TITLE
[suggestion]click on addon icon to set mode

### ISSUE THREAD

**Issue by bitpixl** [JustOff/cookies-exterminator#4]
Thanks for developing this addon as SDC is sadly no longer being developed. Would it be possible to implement the option to just click on the addon's icon to set the mode? so for example: 1st click on icon, the site is whitelisted and the icon turns green. 2nd click on icon: Keep until browser exit is set and icon turns brown. 3rd click: Clean as soon as possible and icon turns red. Or only have the first option enabled that way (whitelist). The menu could then still be used using a right click on the icon (or you can set the icon clicks on the right mouse button).

Keep up the great work!

**Comment by JustOff** [comment]
Well, I'll think it over.

PS: Btw, are you aware the CE is not compatible with Firefox 57+ and currently there are no plans to rewrite it using WebExtensions API?

**Comment by bitpixl** [comment]
I didn't know CE will stop when FF 57+ is released. In that case, leave it as it is and I'll keep on using it until it doesn't work anymore.

**Comment by JustOff** [comment]
As for Firefox 57+ you could take a look at [Cookie-AutoDelete](https://github.com/mrdokenny/Cookie-AutoDelete).  However [it can't deal with localStorage at the moment](https://github.com/mrdokenny/Cookie-AutoDelete/issues/44) and it is also limited in the tracking method and could miss some cookies.
