### ISSUE TITLE
clears cookies, but not /storage/default

### ISSUE THREAD

**Issue by atomGit** [JustOff/cookies-exterminator#5]
Linux
FF 55.2.0
CE 2.9.0
cookie policy: allow 1st party, deny 3rd party
no site permissions set

i notice when i visit YouTube it's adding an object in `/storage/default` and CE isn't clearing it - it is removing the cookies however

**Comment by JustOff** [comment]
> FF 55.2.0

There is no such FF version.

> when i visit YouTube it's adding an object in /storage/default and CE isn't clearing it

I can't reproduce this problem using clean profile + CE 2.9.0 in FF 56.0.

**Comment by atomGit** [comment]
55.0.2

i can't reproduce it reliably either, but it does happen - yesterday i watched hours of YouTube vids and nothing was stored

**Comment by JustOff** [comment]
I'm afraid that I will not be able to solve this problem until we find steps to reproduce it.

Maybe at least you remember the exact name of the folder in `/storage/default` that was not deleted? Was it `https+++www.youtube.com` or something different from `*.youtube.com`?

**Comment by atomGit** [comment]
it had "youtube.com" in the folder name - there was also another instance where another site stored data that wasn't deleted

and as i wrote this i just checked /storage/local again and...

`https+++www.youtube.com^firstPartyDomain=youtube.com`

this was after i closed the tab and waited 10 sec.

the page i happened to be visiting was
`https://www.youtube.com/watch?v=Nov26ii8vbs`
don't laugh :)

i loaded and unloaded that page several times to see if the storage got deleted and it didn't, so i deleted it manually and reopened the URL and no storage item appeared until i allowed cookies in uMatrix, after which i closed the tab once more and the storage item stayed

so on a clean profile, i don't doubt it works, but many users that use CE are likely to also run uMatrix or uBlock O

all that said, i have no problem if you want to put this to bed for the time being until all this WebExt stuff gets sorted out because i know this has caused problems with uBO and uM and page loading, etc., etc.

**Comment by JustOff** [comment]
> https+++www.youtube.com^firstPartyDomain=youtube.com

It seem that you manually enabled `privacy.firstparty.isolate` in `about:config` and `quotaManager.clearStoragesForPrincipal()` does not work properly in this mode. 

Unfortunately I can do nothing about it and I dubt that this API would ever be fixed for XUL/XPCOM add-ons, while CE isn't going to become WebExtension :flushed:

**Comment by atomGit** [comment]
ah! i knew there 2 prefs that could interfere with add-ons that handle storage, but i couldn't remember which ones - sorry, i should have researched this earlier

the other pref is `privacy.firstparty.isolate.restrict_opener_access` - is 'false' ok with that one?

> ... while CE isn't going to become WebExtension

[Cookie AutoDelete](https://addons.mozilla.org/en-US/firefox/addon/cookie-autodelete/) is a WebExt, but it doesn't yet do LocalStorage and, depending on the API, i suppose it may never ... we'll see - i'm hoping the add-on devs are pushing this

**Comment by JustOff** [comment]
Sorry, but I only tested CE with default First Party Isolation settings and can not help you with further research on this.
