### ISSUE TITLE
Cookies and storage not removed when navigating to chrome url

### ISSUE THREAD

**Issue by atomGit** [JustOff/cookies-exterminator#6]
hi JustOff - i realize with the transition to WebExtensions that you may no longer be supporting CE, but we'll give it a try anyway...

for example, let's say we have youtube.com opened in a tab - if i then load a `chrome://` URI in that same tab, the youtube storage is not removed

waterfox 56.1.0 (supports legacy extensions)
CE 2.9.0

**Comment by JustOff** [comment]
What about cookies, are they cleaned successfully? Do you have multiprocess mode enabled?

**Comment by atomGit** [comment]
actually when i said 'storage' i meant 'cookies'

there is no difference whether multi-process is enabled - i thought it couldn't be enabled with legacy extensions, but i enabled it, restarted and checked about:support and apparently it is working - still doesn't solve the problem though

**Comment by JustOff** [comment]
Actually CE does not work properly with local storage when e10s is enabled, so better don't turn it on.

Well, now I see where is the problem, I'll try to add workaround for the `url`->`chrome` sequence.

**Comment by JustOff** [comment]
Try [2.9.1b1](https://github.com/JustOff/cookies-exterminator/releases/download/2.9.0/cookexterm-2.9.1b1.xpi).

**Comment by atomGit** [comment]
works like a champ :)

thanks for your work
