### ISSUE TITLE
Easier To See Toolbar Icons?

### ISSUE THREAD

**Issue by Francewhoa** [JustOff/cookies-exterminator#8]
<a name="summary"></a>
## [Summary](#summary)

I love it this add-on. It's easy to use. 

This ticket is a suggested new feature for Cookies Exterminator version 2.9.2. The Firefox add-on at https://addons.mozilla.org/en-US/firefox/addon/cookies-exterminator/

Any volunteer for a patch for that new feature? The team at Ubertus.org would be happy to contribute testing and documentation.

<a name="user-story"></a>
## [User Story](#user-story)

As a user of Cookies Exterminator, when "Active mode" is disabled, on large screen, I need to be able easily and quickly see the [toolbar icon colors](https://user-images.githubusercontent.com/119942/40285242-dede1d90-5c4e-11e8-8ccd-3c2ad47a8daf.png), so that I know the present color. Green, or brown, or red.

<a name="assumptions"></a>
### [Assumptions](#assumptions)

* Assumes this screenshot below shows the challenge. This is the present green icon for whitelist. When "Active move" is disabled. Notice that the toolbar icon design color is small and hard to see on large screens. It is a tiny dot inside a circle. It does work :) But it is just hard to see :(
![screenshot---challenge---2018-05-20---selection_001---francewhoa](https://user-images.githubusercontent.com/119942/40285242-dede1d90-5c4e-11e8-8ccd-3c2ad47a8daf.png)
* Assumes by large screen we means 24 inches or more
* Assumes using:
  * Add-on 2.9.2
  * Firefox or Tor Browser 52.8.0 (64-bit)
  * Debian 8 Jessie 64-bit
  * GNOME 3.14.1

<a name="options-to-consider"></a>
## [Options to consider](#options-to-consider)

The following are options to consider to improve the usability

<a name="option-1"></a>
### [Option 1](#option-1)

How about a bigger design inside the toolbar icon? How about a bigger circle?
![mockup---suggestion---2---2018-05-20---selection_001---francewhoa](https://user-images.githubusercontent.com/119942/40285424-a9a022b6-5c50-11e8-8d50-52431893ed5b.png)

<a name="option-2"></a>
### [Option 2](#option-2)

On color change, change the whole icon color. Instead of changing only the small dot inside the circle. Similar to "Active move" is enabled. Then find another design for "Active move" is disabled. How about a small square around the top right? With a toggle design. With the letter "A" for "Activated", and the letter "D" for "Deactivated/Disabled".
![mockup---suggestion---3---activated---2018-05-20---selection_001---francewhoa](https://user-images.githubusercontent.com/119942/40285557-56e26cee-5c52-11e8-91f3-a39094b9d4cd.png)
 
![mockup---suggestion---3---deactivated---2018-05-20---selection_001---francewhoa](https://user-images.githubusercontent.com/119942/40285559-5aa70c4a-5c52-11e8-896c-a72c4142578c.png)

Image source at https://github.com/JustOff/cookies-exterminator/blob/master/skin/whitelisted.png

<a name="notes"></a>
### [Note](note)

I understand this add-on is no longer develop for Firefox 57+. While at the same time this add-on is still useful and working fine with some browsers with long term support (LTS or ESR). Such as the present [Tor Browser](https://www.torproject.org/projects/torbrowser.html.en) and Firefox 52.x.

**Comment by JustOff** [comment]
Thank you for your suggestion, but at the moment I'm inclined to reject it. I'm sorry if you are disappointed, but probably you'd better create icons that you like yourself and connect them by replacing the existing ones. You can use [CE Skin](https://github.com/JustOff/cookies-exterminator/releases/download/2.9.3/cookexterm-skin-1.0.0.xpi) add-on as a template to make your changes independent from CE updates.

**Comment by Francewhoa** [comment]
Thanks for your reply and the information JustOff :)
