### ISSUE TITLE
[question] extension styling for notification

### ISSUE THREAD

**Issue by L-a-n-g-o-l-i-e-r-s** [JustOff/cookies-exterminator#9]
Hi there,

Do you know what specific values would be needed to change the notification to black background and white text? I've tried some various generic user styles for extensions, they don't work for this.

The legacy dark backgrounds light text turns it black, it's too slow though for it and it still appears white originally, so it must be possible if using a legacy style theme manager.

I couldn't find the value I was looking for when I was looking at the source, but I'm no developer.

Appreciate your time, thanks for your hard work.

**Comment by JustOff** [comment]
You can add something like this
```
#alertBox {
     background-color: blue !important;
     color: yellow !important;
}
```
to the [UserChrome.css](http://kb.mozillazine.org/index.php?title=UserChrome.css).
